services:
    postgres:
        ports:
            - 5432:5432
        container_name: postgres
        environment:
            - POSTGRES_PASSWORD=root
        image: postgres
        networks:
            - calcnet
    pgadmin4:
        ports:
            - 5050:5050
        environment:
            - PGADMIN_DEFAULT_EMAIL=email@email.email
            - PGADMIN_DEFAULT_PASSWORD=root
        image: dpage/pgadmin4
        networks:
            - calcnet

networks:
    calcnet:
        driver: bridge
        name: calcnet